FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG STRIPE_SECRET_KEY
ARG DATABASE_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV DATABASE_URL=$DATABASE_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]